version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "warehouse-notification-service"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "SenderEmail=alerts@warehouse-ops.com TwilioAccountSid= TwilioAuthToken= TwilioPhoneNumber="
resolve_s3 = true
